version: "2"

services:
  api:
    image: felipearmat/saleor-vue
    env_file: common.prod.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      # add the server hosts - in this case production host is 45.33.93.38
      - ALLOWED_CLIENT_HOSTS=localhost,127.0.0.1,45.33.93.38
      - ALLOWED_HOSTS=localhost,127.0.0.1,45.33.93.38
      # don't generate thumbnails on demand
      - CREATE_IMAGES_ON_DEMAND=False
      - MEDIA_URL=http://saleor-api.mbweb.com.br/media/
      # set debug to False for production mode
      - DEBUG=False

  storefront:
    image: felipearmat/saleor-storefront-vue
    ports:
      - 3000:80
    env_file: common.prod.env

  dashboard:
    image: felipearmat/saleor-dashboard-vue
    ports:
      - 9000:80
    env_file: common.prod.env

  db:
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  worker:
    image: felipearmat/saleor-vue
    env_file: common.prod.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      # add the server hosts - in this case production host is 45.33.93.38
      - ALLOWED_CLIENT_HOSTS=localhost,127.0.0.1,45.33.93.38
      - ALLOWED_HOSTS=localhost,127.0.0.1,45.33.93.38
      # don't generate thumbnails on demand
      - CREATE_IMAGES_ON_DEMAND=False
      - MEDIA_URL=http://saleor-api.mbweb.com.br/media/
      # set debug to False for production mode
      - DEBUG=False
