version: "2"

services:
  api:
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    env_file: common.prod.env
    volumes:
      - ./saleor/nginx/ssl:/etc/nginx/sites-available/
      - /etc/letsencrypt/live/saleor:/etc/cert/
    environment:
      - JAEGER_AGENT_HOST=jaeger
      # add the server hosts - in this case production host is 45.33.93.38
      - ALLOWED_CLIENT_HOSTS=localhost,127.0.0.1,0.0.0.0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      # don't generate thumbnails on demand
      - CREATE_IMAGES_ON_DEMAND=False
      - MEDIA_URL=http://localhost:8000/media/
      # set debug to False for production mode
      - DEBUG=False

  storefront:
    build:
      context: ./saleor-storefront
      dockerfile: ./Dockerfile
    volumes:
      - ./saleor-storefront/nginx/ssl:/etc/nginx/sites-available/
      - /etc/letsencrypt/live/saleor-storefront:/etc/cert/
    ports:
      - 3000:80
    env_file: common.prod.env

  dashboard:
    build:
      context: ./saleor-dashboard
      dockerfile: ./Dockerfile
    volumes:
      - ./saleor-dashboard/nginx/ssl:/etc/nginx/sites-available/
      - /etc/letsencrypt/live/saleor-dashboard:/etc/cert/
    ports:
      - 9000:80
    env_file: common.prod.env

  db:
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  worker:
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    env_file: common.prod.env
    volumes:
      - ./saleor/nginx/ssl:/etc/nginx/sites-available/
    environment:
      - JAEGER_AGENT_HOST=jaeger
      # add the server hosts - in this case production host is 45.33.93.38
      - ALLOWED_CLIENT_HOSTS=localhost,127.0.0.1,0.0.0.0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      # don't generate thumbnails on demand
      - CREATE_IMAGES_ON_DEMAND=False
      - MEDIA_URL=http://localhost:8000/media/
      # set debug to False for production mode
      - DEBUG=False
